export const FETCH_SERVICES_DATA_REQUEST = 'FETCH_SERVICES_DATA_REQUEST';
export const FETCH_SERVICES_DATA_SUCCESS = 'FETCH_SERVICES_DATA_SUCCESS';
export const FETCH_SERVICES_DATA_FAILED = 'FETCH_SERVICES_DATA_FAILED';