export const SEND_APP_LINK_REQUEST = "SEND_APP_LINK_REQUEST";
export const SEND_APP_LINK_SUCCESS = "SEND_APP_LINK_SUCCESS";
export const SEND_APP_LINK_FAILED = "SEND_APP_LINK_FAILED";

export const DOCTOR_LOCATION_REQUEST = "DOCTOR_LOCATION_REQUEST";
export const DOCTOR_LOCATION_SUCCESS = "DOCTOR_LOCATION_SUCCESS";
export const DOCTOR_LOCATION_FAILED = "DOCTOR_LOCATION_FAILED";
