export const GET_IN_TOUCH_API_REQUEST = 'GET_IN_TOUCH_API_REQUEST';
export const GET_IN_TOUCH_API_SUCCESS = 'GET_IN_TOUCH_API_SUCCESS';
export const GET_IN_TOUCH_API_FAILED = 'GET_IN_TOUCH_API_FAILED';