export const FETCH_BOOK_DOCTORS_DATA_REQUEST = 'FETCH_BOOK_DOCTORS_DATA_REQUEST';
export const FETCH_BOOK_DOCTORS_DATA_SUCCESS = 'FETCH_BOOK_DOCTORS_DATA_SUCCESS';
export const FETCH_BOOK_DOCTORS_DATA_FAILED = 'FETCH_BOOK_DOCTORS_DATA_FAILED';