export const FETCH_VIDEOS_DATA_REQUEST = "FETCH_VIDEOS_DATA_REQUEST";
export const FETCH_VIDEOS_DATA_SUCCESS = "FETCH_VIDEOS_DATA_SUCCESS";
export const FETCH_VIDEOS_DATA_FAILED = "FETCH_VIDEOS_DATA_FAILED";
export const SET_VIDEO_STATUS = "SET_VIDEO_STATUS";