export const FETCH_TESTIMONIALS_DATA_REQUEST = 'FETCH_TESTIMONIALS_DATA_REQUEST';
export const FETCH_TESTIMONIALS_DATA_SUCCESS = 'FETCH_TESTIMONIALS_DATA_SUCCESS';
export const FETCH_TESTIMONIALS_DATA_FAILED = 'FETCH_TESTIMONIALS_DATA_FAILED';